---

- name: Ensure MongoDB is present
  apt: pkg=mongodb-org state=latest

- name: Ensure MongoDB is started
  service: name=mongod state=started enabled=yes

- name: Ensure MongoDB Configuration
  template: src=mongod.conf.j2 dest=/etc/mongod.conf owner=root group=root mode=0644
  notify: MongoDB Restart
